-keep public class app.revanced.manager.plugin.downloader.apkmirror.* { *; }
-keep public class app.revanced.manager.plugin.downloader.apkpure.* { *; }
-keep public class app.revanced.manager.plugin.downloader.apkcombo.* { *; }
